DELETE FROM VersionFeature;
INSERT INTO VersionFeature ([VersionID], [FeatureDescription]) VALUES (1,'address verification')
INSERT INTO VersionFeature ([VersionID], [FeatureDescription]) VALUES (1,'login module')
INSERT INTO VersionFeature ([VersionID], [FeatureDescription]) VALUES (1,'patient profile')
INSERT INTO VersionFeature ([VersionID], [FeatureDescription]) VALUES (1,'patient registration')
INSERT INTO VersionFeature ([VersionID], [FeatureDescription]) VALUES (1,'patient release form')
INSERT INTO VersionFeature ([VersionID], [FeatureDescription]) VALUES (1,'physician profile')
INSERT INTO VersionFeature ([VersionID], [FeatureDescription]) VALUES (2,'login module')
INSERT INTO VersionFeature ([VersionID], [FeatureDescription]) VALUES (2,'patient profile')
INSERT INTO VersionFeature ([VersionID], [FeatureDescription]) VALUES (2,'patient registration')
INSERT INTO VersionFeature ([VersionID], [FeatureDescription]) VALUES (2,'patient release form')
INSERT INTO VersionFeature ([VersionID], [FeatureDescription]) VALUES (2,'physician profile')
INSERT INTO VersionFeature ([VersionID], [FeatureDescription]) VALUES (3,'address verification')
INSERT INTO VersionFeature ([VersionID], [FeatureDescription]) VALUES (4,'patient authentication')
INSERT INTO VersionFeature ([VersionID], [FeatureDescription]) VALUES (4,'patient e-bill')
INSERT INTO VersionFeature ([VersionID], [FeatureDescription]) VALUES (4,'patient medication form')
INSERT INTO VersionFeature ([VersionID], [FeatureDescription]) VALUES (4,'patient reporting')
INSERT INTO VersionFeature ([VersionID], [FeatureDescription]) VALUES (5,'patient authentication')
INSERT INTO VersionFeature ([VersionID], [FeatureDescription]) VALUES (5,'patient e-bill')
INSERT INTO VersionFeature ([VersionID], [FeatureDescription]) VALUES (5,'patient medication form')
INSERT INTO VersionFeature ([VersionID], [FeatureDescription]) VALUES (5,'patient reporting bug fix')
INSERT INTO VersionFeature ([VersionID], [FeatureDescription]) VALUES (5,'patient reporting')