DELETE FROM Release;
INSERT INTO Release ([ReleaseID], [VersionID], [IterationID], [BranchID], [ReleaseNotes], [ReleaseDate], [ReleaseType]) VALUES (1,1,2,1,'Best Release Yet','1/1/2000','new product release')
INSERT INTO Release ([ReleaseID], [VersionID], [IterationID], [BranchID], [ReleaseNotes], [ReleaseDate], [ReleaseType]) VALUES (2,2,2,2,'Best Release Yet','1/1/2000','new product release')
INSERT INTO Release ([ReleaseID], [VersionID], [IterationID], [BranchID], [ReleaseNotes], [ReleaseDate], [ReleaseType]) VALUES (3,3,2,3,'Best Release Yet','1/1/2000','new product release')
INSERT INTO Release ([ReleaseID], [VersionID], [IterationID], [BranchID], [ReleaseNotes], [ReleaseDate], [ReleaseType]) VALUES (4,4,2,2,'Best Release Yet','1/1/2000','new product release')
INSERT INTO Release ([ReleaseID], [VersionID], [IterationID], [BranchID], [ReleaseNotes], [ReleaseDate], [ReleaseType]) VALUES (5,5,2,1,'Best Release Yet','1/1/2000','new product release')
INSERT INTO Release ([ReleaseID], [VersionID], [IterationID], [BranchID], [ReleaseNotes], [ReleaseDate], [ReleaseType]) VALUES (6,1,1,2,'Best Release Yet','1/1/2000','new product release')
INSERT INTO Release ([ReleaseID], [VersionID], [IterationID], [BranchID], [ReleaseNotes], [ReleaseDate], [ReleaseType]) VALUES (7,2,1,1,'Best Release Yet','1/1/2000','new product release')
INSERT INTO Release ([ReleaseID], [VersionID], [IterationID], [BranchID], [ReleaseNotes], [ReleaseDate], [ReleaseType]) VALUES (8,3,1,3,'Best Release Yet','1/1/2000','new product release')
INSERT INTO Release ([ReleaseID], [VersionID], [IterationID], [BranchID], [ReleaseNotes], [ReleaseDate], [ReleaseType]) VALUES (9,4,1,1,'Best Release Yet','1/1/2000','new product release')
INSERT INTO Release ([ReleaseID], [VersionID], [IterationID], [BranchID], [ReleaseNotes], [ReleaseDate], [ReleaseType]) VALUES (10,5,1,2,'Best Release Yet','1/1/2000','new product release')
INSERT INTO Release ([ReleaseID], [VersionID], [IterationID], [BranchID], [ReleaseNotes], [ReleaseDate], [ReleaseType]) VALUES (11,1,1,1,'Best Release Yet','1/1/2000','new product release')
INSERT INTO Release ([ReleaseID], [VersionID], [IterationID], [BranchID], [ReleaseNotes], [ReleaseDate], [ReleaseType]) VALUES (12,2,1,2,'Pretty good release','1/1/2000','new product release')
INSERT INTO Release ([ReleaseID], [VersionID], [IterationID], [BranchID], [ReleaseNotes], [ReleaseDate], [ReleaseType]) VALUES (13,3,1,1,'Pretty good release','5/1/2000','new features release')
INSERT INTO Release ([ReleaseID], [VersionID], [IterationID], [BranchID], [ReleaseNotes], [ReleaseDate], [ReleaseType]) VALUES (14,4,1,3,'Pretty good release','5/1/2000','new features release')
INSERT INTO Release ([ReleaseID], [VersionID], [IterationID], [BranchID], [ReleaseNotes], [ReleaseDate], [ReleaseType]) VALUES (15,5,1,1,'Pretty good release','5/1/2000','new features release')
INSERT INTO Release ([ReleaseID], [VersionID], [IterationID], [BranchID], [ReleaseNotes], [ReleaseDate], [ReleaseType]) VALUES (16,1,2,2,'Pretty good release','5/1/2000','new features release')
INSERT INTO Release ([ReleaseID], [VersionID], [IterationID], [BranchID], [ReleaseNotes], [ReleaseDate], [ReleaseType]) VALUES (17,2,2,1,'Pretty good release','5/1/2000','new features release')
INSERT INTO Release ([ReleaseID], [VersionID], [IterationID], [BranchID], [ReleaseNotes], [ReleaseDate], [ReleaseType]) VALUES (18,3,2,2,'Pretty good release','5/1/2000','new features release')
INSERT INTO Release ([ReleaseID], [VersionID], [IterationID], [BranchID], [ReleaseNotes], [ReleaseDate], [ReleaseType]) VALUES (19,4,2,1,'Pretty good release','5/1/2000','new features release')
INSERT INTO Release ([ReleaseID], [VersionID], [IterationID], [BranchID], [ReleaseNotes], [ReleaseDate], [ReleaseType]) VALUES (20,5,2,3,'Pretty good release','5/1/2000','new features release')
INSERT INTO Release ([ReleaseID], [VersionID], [IterationID], [BranchID], [ReleaseNotes], [ReleaseDate], [ReleaseType]) VALUES (21,1,2,1,'Pretty good release','6/13/2000','bug-fix release')