-- Insert the features
INSERT INTO Feature ([FeatureDescription]) VALUES ('address verification')
INSERT INTO Feature ([FeatureDescription]) VALUES ('login module')
INSERT INTO Feature ([FeatureDescription]) VALUES ('patient authentication')
INSERT INTO Feature ([FeatureDescription]) VALUES ('patient e-bill')
INSERT INTO Feature ([FeatureDescription]) VALUES ('patient medication form')
INSERT INTO Feature ([FeatureDescription]) VALUES ('patient profile')
INSERT INTO Feature ([FeatureDescription]) VALUES ('patient registration')
INSERT INTO Feature ([FeatureDescription]) VALUES ('patient release form')
INSERT INTO Feature ([FeatureDescription]) VALUES ('patient reporting bug fix')
INSERT INTO Feature ([FeatureDescription]) VALUES ('patient reporting')
INSERT INTO Feature ([FeatureDescription]) VALUES ('physician profile')